# Author: Guilherme Bach
# 2020-03-14
# v1.0

version: '3.1'
services:
  php:
    build: ./dockerfiles/php/
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - "./:/var/www/html/"
      - "./dockerfiles/config/.env:/var/www/html/.env"
      # - ./dockerfiles/config/php.ini:/usr/local/etc/php/php.ini
    command: php -S 0.0.0.0:9000 -t public   
  db:
    image: mysql:8
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: consultorio
      MYSQL_DATABASE: consultorio_alura
    volumes:
      - ./mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    driver: local